source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'FetchedResultsCoordinator_Example', :exclusive => true do
  pod "FetchedResultsCoordinator", :path => "../"
end

target 'FetchedResultsCoordinator_Tests', :exclusive => true do
  pod "FetchedResultsCoordinator", :path => "../"
  pod 'Specta'
  pod 'Expecta'
  pod 'OCMock'
  pod 'Quick'
  pod 'Nimble'
end
